### ISSUE TITLE
Wrong rendering when a particle with no power of two image is rendered

### ISSUE THREAD

**Issue by lishunan12351** [effekseer/Effekseer#117] opened 2018-05-16 06:54 UTC
int the effect editer
![a1](https://user-images.githubusercontent.com/15611020/40101025-a70e8bc2-5918-11e8-8a9a-758d78b32d26.gif)

but in game
![a2](https://user-images.githubusercontent.com/15611020/40101068-cd820b4e-5918-11e8-87fd-e571fb1dc65f.gif)
I don't know where to check. It's strange.

**Comment by lishunan12351** [comment] 2018-05-16 07:00
i try to change a another texture,then there is no problem
![a3](https://user-images.githubusercontent.com/15611020/40101216-5a39b820-5919-11e8-93e0-d69084a40213.gif)
![a4](https://user-images.githubusercontent.com/15611020/40101365-ca5d0e4a-5919-11e8-9a10-9653ad88ec4c.gif)

**Comment by lishunan12351** [comment] 2018-05-16 07:01
this is texture i use
![dilie](https://user-images.githubusercontent.com/15611020/40101449-0953fb2c-591a-11e8-86b1-6b1e8c18f211.png)

**Comment by durswd** [comment] 2018-05-16 07:47
I seem that Z write is on and this effect is rendered before rendering ground.
If it is true, please make Z write off or render effect after rendering ground.
if it is not true, please send this effect.

In addition, I recommend to make Configuration Fixed in Sprite if a sprite is on a ground.

**Comment by lishunan12351** [comment] 2018-05-16 07:56
this is the project file
[test.zip](https://github.com/effekseer/Effekseer/files/2008044/test.zip)

**Comment by lishunan12351** [comment] 2018-05-16 08:10
in fact,i use the top sprite as Billboard.It looks like the ground is split.

**Comment by durswd** [comment] 2018-05-16 14:56
I try it.

>this is the project file
>test.zip

is this wrong file?
I need to correct effect and wrong effect.

**Comment by lishunan12351** [comment] 2018-05-17 02:51
yes

**Comment by durswd** [comment] 2018-05-17 16:55
I tried. But I cannot reproduce this problem on Windows.
(I resized texture size. Because no power of two size texture cannot generate mipmap)
There is a possibility that no power of two size texture causes this problem.

Please change a texture size so that the size of texture becomes power of two.
If still causes this problem, would you send this project for me?

**Comment by lishunan12351** [comment] 2018-05-18 03:09
ok,i resize the texture size,it's ok,thanks！

**Comment by durswd** [comment] 2018-05-18 12:42
Is it solved?

**Comment by lishunan12351** [comment] 2018-05-22 11:30
yes,thanks!

**Comment by lishunan12351** [comment] 2018-05-22 11:33
another question，Does the editor support the export of .efk files with the command line?

**Comment by durswd** [comment] 2018-05-22 12:39
Please read it.

https://effekseer.github.io/Help_Tool/en/ToolReference/top.html

for example

Effekseer -cui -in xxx.efjproj -e xxx.efk  -m 1.0

**Comment by lishunan12351** [comment] 2018-05-23 02:13
ok,thanks

**Comment by lishunan12351** [comment] 2018-05-23 09:47
thanks

**Closed** 2018-05-31 07:36 UTC
